name: Exemple Variables d'Environnement

on:
  push:
    branches:
      - main

jobs:
  show-message:
    runs-on: ubuntu-latest

    # ✅ Définir une variable d'environnement pour tout le job
    env:
      MESSAGE: "Déploiement réussi"

    steps:
      # Étape 1 : Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Afficher la variable
      - name: Afficher la variable MESSAGE
        run: echo "$MESSAGE"
